### ISSUE TITLE
Deprication function with PHP 8.1

### ISSUE THREAD

**Issue by kylehuynh205** [digitalutsc/citation_select#19]
# To reproduce: 
* Have isle-dc in with PHP 8.1 and with Drupal 9.5 OR Drupal 10
* Make sure citation_select module is `bibcite-update` branch and bibicite module is in Dev branch (if not run `composer require 'drupal/bibcite:3.0.x-dev@dev'`) 
* Import the citation select config https://github.com/digitalutsc/islandora-sandbox/blob/config_sync_context/config/sync/citation_select.settings.yml
* Create an object with data on Date, Linked Agent fields filled. 
* Got to that object and start using the the object: 
* Go to the log and see these Deprecated error: 

````
Message Deprecated function: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in Seboettg\CiteProc\Util\StringHelper::removeBrackets() (line 315 of /var/www/drupal/vendor/seboettg/citeproc-php/src/Util/StringHelper.php)
#0 /var/www/drupal/web/core/includes/bootstrap.inc(347): _drupal_error_handler_real()
#1 [internal function]: _drupal_error_handler()
#2 /var/www/drupal/vendor/seboettg/citeproc-php/src/Util/StringHelper.php(315): str_replace()
#3 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Date/Date.php(375): Seboettg\CiteProc\Util\StringHelper::removeBrackets()
#4 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Date/Date.php(216): Seboettg\CiteProc\Rendering\Date\Date->cleanDate()
#5 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Date/Date.php(165): Seboettg\CiteProc\Rendering\Date\Date->createDateTime()
#6 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Group.php(113): Seboettg\CiteProc\Rendering\Date\Date->render()
#7 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Choose/ChooseIf.php(79): Seboettg\CiteProc\Rendering\Group->render()
#8 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Choose/Choose.php(98): Seboettg\CiteProc\Rendering\Choose\ChooseIf->render()
#9 /var/www/drupal/vendor/seboettg/citeproc-php/src/Style/Macro.php(86): Seboettg\CiteProc\Rendering\Choose\Choose->render()
#10 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Text.php(290): Seboettg\CiteProc\Style\Macro->render()
#11 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Text.php(120): Seboettg\CiteProc\Rendering\Text->renderMacro()
#12 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Choose/ChooseIf.php(79): Seboettg\CiteProc\Rendering\Text->render()
#13 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Choose/Choose.php(105): Seboettg\CiteProc\Rendering\Choose\ChooseIf->render()
#14 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Group.php(113): Seboettg\CiteProc\Rendering\Choose\Choose->render()
#15 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Group.php(113): Seboettg\CiteProc\Rendering\Group->render()
#16 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Layout.php(130): Seboettg\CiteProc\Rendering\Group->render()
#17 /var/www/drupal/vendor/seboettg/citeproc-php/src/Rendering/Layout.php(97): Seboettg\CiteProc\Rendering\Layout->renderSingle()
#18 /var/www/drupal/vendor/seboettg/citeproc-php/src/Style/Bibliography.php(76): Seboettg\CiteProc\Rendering\Layout->render()
#19 /var/www/drupal/vendor/seboettg/citeproc-php/src/CiteProc.php(137): Seboettg\CiteProc\Style\Bibliography->render()
#20 /var/www/drupal/vendor/seboettg/citeproc-php/src/CiteProc.php(183): Seboettg\CiteProc\CiteProc->bibliography()
#21 /var/www/drupal/web/modules/contrib/bibcite/src/Plugin/BibCiteProcessor/CiteprocPhp.php(67): Seboettg\CiteProc\CiteProc->render()
#22 /var/www/drupal/web/modules/contrib/bibcite/src/CitationStyler.php(92): Drupal\bibcite\Plugin\BibCiteProcessor\CiteprocPhp->render()
#23 /var/www/drupal/web/modules/contrib/citation_select/src/Form/SelectCitationForm.php(163): Drupal\bibcite\CitationStyler->render()
#24 [internal function]: Drupal\citation_select\Form\SelectCitationForm->getBibliography()
#25 /var/www/drupal/web/core/lib/Drupal/Core/Form/FormAjaxResponseBuilder.php(69): call_user_func_array()
#26 /var/www/drupal/web/core/lib/Drupal/Core/Form/EventSubscriber/FormAjaxSubscriber.php(109): Drupal\Core\Form\FormAjaxResponseBuilder->buildResponse()
#27 [internal function]: Drupal\Core\Form\EventSubscriber\FormAjaxSubscriber->onException()
#28 /var/www/drupal/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(142): call_user_func()
#29 /var/www/drupal/vendor/symfony/http-kernel/HttpKernel.php(229): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#30 /var/www/drupal/vendor/symfony/http-kernel/HttpKernel.php(92): Symfony\Component\HttpKernel\HttpKernel->handleThrowable()
#31 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#32 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#33 /var/www/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#34 /var/www/drupal/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#35 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#36 /var/www/drupal/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#37 /var/www/drupal/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#38 /var/www/drupal/web/core/lib/Drupal/Core/DrupalKernel.php(718): Stack\StackedHttpKernel->handle()
#39 /var/www/drupal/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#40 {main}
````

# Goal
* Troubleshoot and find the fix.
* If not, Find the fix online ? 
* If not, find or create patch to fix that Deprecated error.

**Comment by Natkeeran** [comment]
This dependency has been removed.
