### ISSUE TITLE
When date field has date range, the citation is not generated

### ISSUE THREAD

**Issue by Natkeeran** [digitalutsc/citation_select#21]
https://menus.digital.utsc.utoronto.ca/61220/utsc41580

https://git.drupalcode.org/project/citation_select (beta5)

```
Error: Call to undefined method EDTF\Model\Interval::getYear() in Drupal\citation_select\Plugin\CitationFieldFormatter\EdtfDateFormatter->parseDate() (line 33 of /var/www/D10-menus/web/modules/contrib/citation_select/src/Plugin/CitationFieldFormatter/EdtfDateFormatter.php)

#0 /var/www/D10-menus/web/modules/contrib/citation_select/src/CitationFieldFormatterBase.php(27): Drupal\citation_select\Plugin\CitationFieldFormatter\EdtfDateFormatter->parseDate()
#1 /var/www/D10-menus/web/modules/contrib/citation_select/src/CitationProcessorService.php(96): Drupal\citation_select\CitationFieldFormatterBase->formatMultiple()
#2 /var/www/D10-menus/web/modules/contrib/citation_select/src/Form/SelectCitationForm.php(160): Drupal\citation_select\CitationProcessorService->getCitationArray()
#3 [internal function]: Drupal\citation_select\Form\SelectCitationForm->getBibliography()
#4 /var/www/D10-menus/web/core/lib/Drupal/Core/Form/FormAjaxResponseBuilder.php(69): call_user_func_array()
#5 /var/www/D10-menus/web/core/lib/Drupal/Core/Form/EventSubscriber/FormAjaxSubscriber.php(109): Drupal\Core\Form\FormAjaxResponseBuilder->buildResponse()
#6 [internal function]: Drupal\Core\Form\EventSubscriber\FormAjaxSubscriber->onException()
#7 /var/www/D10-menus/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func()
#8 /var/www/D10-menus/vendor/symfony/http-kernel/HttpKernel.php(239): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch()
#9 /var/www/D10-menus/vendor/symfony/http-kernel/HttpKernel.php(91): Symfony\Component\HttpKernel\HttpKernel->handleThrowable()
#10 /var/www/D10-menus/web/core/lib/Drupal/Core/StackMiddleware/Session.php(58): Symfony\Component\HttpKernel\HttpKernel->handle()
#11 /var/www/D10-menus/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(48): Drupal\Core\StackMiddleware\Session->handle()
#12 /var/www/D10-menus/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle()
#13 /var/www/D10-menus/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass()
#14 /var/www/D10-menus/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(48): Drupal\page_cache\StackMiddleware\PageCache->handle()
#15 /var/www/D10-menus/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(51): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle()
#16 /var/www/D10-menus/web/core/lib/Drupal/Core/StackMiddleware/StackedHttpKernel.php(51): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle()
#17 /var/www/D10-menus/web/core/lib/Drupal/Core/DrupalKernel.php(704): Drupal\Core\StackMiddleware\StackedHttpKernel->handle()
#18 /var/www/D10-menus/web/index.php(19): Drupal\Core\DrupalKernel->handle()
#19 {main}
```

**Comment by Natkeeran** [comment]
This issue was fixed by Wenbin.  Thank you.
